### ISSUE TITLE
Limiting our research within the USA?

### ISSUE THREAD

**Issue by lirnish** [UBC-MDS/DSCI_522_group29#4]
Hey while doing EDA, I noticed that our data are mostly from the USA and most of the currency is USD (more than 80%). Given that we do not have large enough data for other countries and it is hard to convert currency (so that the salaries are on the same scale), I am thinking of limiting our research within the USA, do you guys agree? Or if you have any other thoughts?

**Comment by AndyYang80** [comment]
I agree, it seems to be the best option since it would be best to limit the scope of our predictions to the area for which we have the most data.
